databases:
  - name: msituguard-db
    databaseName: msituguard
    user: msituguard

services:
  - type: web
    name: msituguard
    env: python
    buildCommand: "./build.sh"
    startCommand: "bash start_render.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: msituguard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
