# Generated by Django 5.2.6 on 2025-10-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_treeprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='carbon_credits_balance',
            field=models.FloatField(default=0.0, help_text='Current carbon credits balance (tonnes CO2)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='estimated_carbon_value_kes',
            field=models.FloatField(default=0.0, help_text='Estimated value of carbon portfolio in KES'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_carbon_credits_earned',
            field=models.FloatField(default=0.0, help_text='Total carbon credits earned all time'),
        ),
        migrations.AddField(
            model_name='treeplanting',
            name='carbon_credits_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treeplanting',
            name='carbon_credits_potential',
            field=models.FloatField(default=0.0, help_text='Potential carbon credits (tonnes CO2/year)'),
        ),
        migrations.AddField(
            model_name='treeplanting',
            name='estimated_annual_co2_kg',
            field=models.FloatField(default=0.0, help_text='Estimated CO2 absorption per year (kg)'),
        ),
        migrations.AddField(
            model_name='treeplanting',
            name='tree_age_months',
            field=models.PositiveIntegerField(default=0, help_text='Age of trees in months'),
        ),
    ]
