# Generated by Django 5.2.6 on 2025-10-04 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_profile_carbon_credits_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sell', 'Sell Credits'), ('fund', 'Fund Project'), ('trade', 'Trade Credits'), ('earn', 'Earn Credits')], max_length=20)),
                ('amount', models.FloatField(help_text='Amount in tonnes CO2')),
                ('value_kes', models.FloatField(default=0.0, help_text='Value in KES')),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.CharField(blank=True, help_text='For project funding', max_length=200)),
                ('buyer_name', models.CharField(blank=True, help_text='For credit sales', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
