# Generated by Django 5.2.6 on 2025-11-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_carbontransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=50)),
                ('rainfall_mm', models.FloatField()),
                ('temperature_c', models.FloatField()),
                ('altitude_m', models.FloatField()),
                ('soil_ph', models.FloatField()),
                ('soil_type', models.CharField(max_length=50)),
            ],
        ),
    ]
