# Generated by Django 5.2.6 on 2025-11-20 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_county_countyspecies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('soil', models.CharField(blank=True, max_length=200, null=True)),
                ('rainfall', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.CharField(blank=True, max_length=100, null=True)),
                ('care_level', models.CharField(blank=True, max_length=100, null=True)),
                ('best_season', models.CharField(blank=True, max_length=200, null=True)),
                ('planting_method', models.CharField(blank=True, max_length=200, null=True)),
                ('water', models.CharField(blank=True, max_length=200, null=True)),
                ('planting_guide', models.JSONField(blank=True, null=True)),
                ('care_instructions', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='altitude_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='altitude_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='best_season',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='climate_zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='rainfall_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='rainfall_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='soil_ph_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='soil_ph_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='soil_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='temperature_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='temperature_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='countyspecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.species'),
        ),
        migrations.AlterUniqueTogether(
            name='countyspecies',
            unique_together={('county', 'species')},
        ),
    ]
