# Generated by Django 5.2.6 on 2025-11-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_species_county_altitude_max_county_altitude_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='altitude_max',
        ),
        migrations.RemoveField(
            model_name='county',
            name='altitude_min',
        ),
        migrations.RemoveField(
            model_name='county',
            name='best_season',
        ),
        migrations.RemoveField(
            model_name='county',
            name='climate_zone',
        ),
        migrations.RemoveField(
            model_name='county',
            name='rainfall_max',
        ),
        migrations.RemoveField(
            model_name='county',
            name='rainfall_min',
        ),
        migrations.RemoveField(
            model_name='county',
            name='soil_ph_max',
        ),
        migrations.RemoveField(
            model_name='county',
            name='soil_ph_min',
        ),
        migrations.RemoveField(
            model_name='county',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='county',
            name='temperature_max',
        ),
        migrations.RemoveField(
            model_name='county',
            name='temperature_min',
        ),
        migrations.AlterField(
            model_name='species',
            name='best_season',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='species',
            name='care_instructions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='species',
            name='care_level',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='species',
            name='planting_guide',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='species',
            name='planting_method',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='species',
            name='rainfall',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='species',
            name='soil',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='temperature',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='species',
            name='water',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.CreateModel(
            name='CountyEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall_mm_min', models.FloatField()),
                ('rainfall_mm_max', models.FloatField()),
                ('temperature_c_min', models.FloatField()),
                ('temperature_c_max', models.FloatField()),
                ('soil_type', models.CharField(max_length=100)),
                ('altitude_m_min', models.FloatField()),
                ('altitude_m_max', models.FloatField()),
                ('soil_ph_min', models.FloatField()),
                ('soil_ph_max', models.FloatField()),
                ('climate_zone', models.CharField(max_length=50)),
                ('best_season', models.CharField(max_length=50)),
                ('county', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='environment', to='App.county')),
            ],
        ),
    ]
