# Generated by Django 5.2.6 on 2025-11-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_remove_county_altitude_max_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countyspecies',
            options={'ordering': ['species_rank', 'species__name']},
        ),
        migrations.AddField(
            model_name='countyspecies',
            name='environmental_match_score',
            field=models.FloatField(default=70.0, help_text='Environmental compatibility score (0-100)'),
        ),
        migrations.AddField(
            model_name='countyspecies',
            name='recommendation_reason',
            field=models.TextField(default='Good species for this area', help_text='Why this species works well in this county'),
        ),
        migrations.AddField(
            model_name='countyspecies',
            name='seasonal_performance',
            field=models.JSONField(default=dict, help_text='Seasonal bonuses/penalties as JSON'),
        ),
        migrations.AddField(
            model_name='countyspecies',
            name='species_rank',
            field=models.IntegerField(default=1, help_text='Ranking of species for this county (1=best, 2=good, etc.)'),
        ),
        migrations.AddField(
            model_name='countyspecies',
            name='survival_rate',
            field=models.FloatField(default=70.0, help_text='Expected survival percentage for this species in this county'),
        ),
    ]
