# Generated by Django 5.2.6 on 2025-11-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_countyspecies_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreward',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='token',
            name='report',
        ),
        migrations.RemoveField(
            model_name='token',
            name='tree_planting',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userreward',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='carbon_credits_balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='estimated_carbon_value_kes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token_balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_carbon_credits_earned',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_tokens_earned',
        ),
        migrations.RemoveField(
            model_name='report',
            name='tokens_awarded',
        ),
        migrations.RemoveField(
            model_name='treeplanting',
            name='carbon_credits_calculated',
        ),
        migrations.RemoveField(
            model_name='treeplanting',
            name='carbon_credits_potential',
        ),
        migrations.RemoveField(
            model_name='treeplanting',
            name='estimated_annual_co2_kg',
        ),
        migrations.RemoveField(
            model_name='treeplanting',
            name='tokens_awarded',
        ),
        migrations.DeleteModel(
            name='CarbonTransaction',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='UserReward',
        ),
    ]
