# Generated by Django 5.2.6 on 2025-12-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_alter_report_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeprediction',
            name='confidence_level',
            field=models.CharField(choices=[('very_high', 'Very High'), ('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='treeprediction',
            name='explanation_reasons',
            field=models.TextField(blank=True, help_text='JSON list of explanation reasons'),
        ),
        migrations.AddField(
            model_name='treeprediction',
            name='model_version',
            field=models.CharField(default='v1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='treeprediction',
            name='risk_factors',
            field=models.TextField(blank=True, help_text='JSON list of identified risks'),
        ),
        migrations.AlterField(
            model_name='treeprediction',
            name='survival_probability',
            field=models.FloatField(help_text='Probability of survival (0-100)'),
        ),
    ]
