# Generated by Django 5.2.6 on 2025-12-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_treeprediction_confidence_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='county',
            name='longitude',
            field=models.FloatField(default=36.0),
        ),
    ]
