# Generated by Django 5.2.6 on 2025-12-15 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_county_latitude_county_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature_c', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('rain_mm_hour', models.FloatField(default=0)),
                ('wind_speed', models.FloatField()),
                ('source', models.CharField(default='OpenWeather', max_length=50)),
                ('cached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='treeprediction',
            name='weather_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.weathersnapshot'),
        ),
    ]
