# Generated by Django 5.2.4 on 2025-11-21 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organisation', 'Organisation')], default='individual', max_length=20),
        ),
    ]
