# Generated by Django 5.2.6 on 2025-11-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeregistration', '0003_alter_tree_user_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='photo_hash',
            field=models.CharField(max_length=64),
        ),
    ]
