# Generated by Django 5.2.6 on 2025-12-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeregistration', '0004_alter_tree_photo_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='detected_county',
            field=models.CharField(blank=True, help_text='Detected county from location service', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='location_name',
            field=models.CharField(blank=True, help_text='Location name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude coordinate', null=True),
        ),
    ]
